// utils/constants.js
const MODULES = [
  { id: 1, name: 'Phishing Detection', iconKey: 'phishing' },
  { id: 2, name: 'Malware Analysis', iconKey: 'malware' },
  { id: 3, name: 'Network Security', iconKey: 'network' },
  { id: 4, name: 'Cloud Security', iconKey: 'cloud' },
  { id: 5, name: 'Mobile Security', iconKey: 'mobile' },
  { id: 6, name: 'IoT Security', iconKey: 'iot' },
  { id: 7, name: 'Social Engineering', iconKey: 'social' },
  { id: 8, name: 'Incident Response', iconKey: 'incident' },
  { id: 9, name: 'Security Compliance', iconKey: 'compliance' },
  { id: 10, name: 'Ethical Hacking', iconKey: 'ethical' },
  { id: 11, name: 'Ransomware Defense', iconKey: 'ransomware' },
  { id: 12, name: 'Data Privacy (GDPR)', iconKey: 'privacy' },
  { id: 13, name: 'Wireless Security', iconKey: 'wireless' },
  { id: 14, name: 'Database Security', iconKey: 'database' },
  { id: 15, name: 'DevSecOps', iconKey: 'devops' },
  // --- 16 to 45 (we'll assign generic keys, but you can customize later) ---
  { id: 16, name: 'Digital Forensics', iconKey: 'forensic' },
  { id: 17, name: 'Threat Intelligence', iconKey: 'threat' },
  { id: 18, name: 'Security Operations (SOC)', iconKey: 'soc' },
  { id: 19, name: 'Identity & Access Management', iconKey: 'iam' },
  { id: 20, name: 'Cryptography', iconKey: 'crypto' },
  { id: 21, name: 'Zero Trust Architecture', iconKey: 'zerotrust' },
  { id: 22, name: 'Supply Chain Security', iconKey: 'supply' },
  { id: 23, name: 'API Security', iconKey: 'api' },
  { id: 24, name: 'Container Security', iconKey: 'container' },
  { id: 25, name: 'Kubernetes Security', iconKey: 'kubernetes' },
  { id: 26, name: 'Serverless Security', iconKey: 'serverless' },
  { id: 27, name: 'AI & Machine Learning Security', iconKey: 'ai' },
  { id: 28, name: 'Quantum Computing Threats', iconKey: 'quantum' },
  { id: 29, name: 'Blockchain Security', iconKey: 'blockchain' },
  { id: 30, name: 'OT/ICS Security', iconKey: 'ot' },
  { id: 31, name: 'Healthcare Security (HIPAA)', iconKey: 'healthcare' },
  { id: 32, name: 'Financial Security (PCI-DSS)', iconKey: 'financial' },
  { id: 33, name: 'E-Commerce Security', iconKey: 'ecommerce' },
  { id: 34, name: 'Insider Threat Detection', iconKey: 'insider' },
  { id: 35, name: 'Physical Security Integration', iconKey: 'physical' },
  { id: 36, name: 'Disaster Recovery & BCP', iconKey: 'disaster' },
  { id: 37, name: 'Security Awareness Training', iconKey: 'awareness' },
  { id: 38, name: 'Risk Management', iconKey: 'risk' },
  { id: 39, name: 'Vulnerability Management', iconKey: 'vuln' },
  { id: 40, name: 'Penetration Testing', iconKey: 'pentest' },
  { id: 41, name: 'Red Team / Blue Team', iconKey: 'redblue' },
  { id: 42, name: 'Cybersecurity Frameworks', iconKey: 'frameworks' },
  { id: 43, name: 'Cloud Forensics', iconKey: 'cloudforensic' },
  { id: 44, name: 'Mobile Forensics', iconKey: 'mobileforensic' },
  { id: 45, name: 'Cyber Law & Ethics', iconKey: 'cyberlaw' }
];

// Scenario categories for each module (for daily scenarios)
const SCENARIO_TYPES = {
  1: ['Spear Phishing', 'Whaling', 'Clone Phishing', 'Smishing', 'Vishing'],
  2: ['Ransomware', 'Trojan', 'Worm', 'Rootkit', 'Spyware'],
  3: ['DDoS', 'MITM', 'DNS Spoofing', 'Packet Sniffing', 'Port Scanning'],
  4: ['Misconfigured S3', 'Account Hijack', 'Insider Threat', 'API Exposure', 'Multi-Cloud'],
  5: ['Malicious App', 'Device Theft', 'OS Vulnerability', 'App Permissions', 'Mobile Phishing'],
  6: ['IoT Botnet', 'Firmware Exploit', 'Default Credentials', 'Network Exposure', 'Physical Access'],
  7: ['Pretexting', 'Baiting', 'Tailgating', 'Quid Pro Quo', 'Dumpster Diving'],
  8: ['Breach Response', 'Containment', 'Eradication', 'Recovery', 'Lessons Learned'],
  9: ['GDPR Violation', 'PCI-DSS Breach', 'HIPAA', 'SOX', 'ISO 27001'],
  10: ['Reconnaissance', 'Exploitation', 'Privilege Escalation', 'Persistence', 'Exfiltration'],
  11: ['Crypto Ransomware', 'Locker Ransomware', 'Doxware', 'Scareware', 'RaaS'],
  12: ['Data Breach', 'Subject Access Request', 'Data Minimization', 'Cross-Border', 'Consent'],
  13: ['Wi-Fi Eavesdropping', 'Bluetooth Exploit', 'RFID Cloning', 'Jamming', 'Evil Twin'],
  14: ['SQL Injection', 'NoSQL Injection', 'Data Exposure', 'Privilege Abuse', 'Backup Theft'],
  15: ['Pipeline Breach', 'Infrastructure as Code', 'Secrets Management', 'Container Escape', 'Shift-Left'],
  16: ['Memory Forensics', 'Disk Forensics', 'Network Forensics', 'Cloud Forensics', 'Mobile Forensics'],
  17: ['Indicator of Compromise', 'Threat Hunting', 'Attribution', 'TTP Analysis', 'CTI Sharing'],
  18: ['SIEM Tuning', 'Alert Fatigue', 'Incident Triage', 'Playbook Execution', 'Post-Incident'],
  19: ['Privilege Creep', 'MFA Bypass', 'SSO Vulnerabilities', 'Role-Based Access', 'Zero Standing'],
  20: ['Symmetric Key', 'Asymmetric Key', 'Hash Collision', 'PKI', 'Quantum Resistance'],
  21: ['Microsegmentation', 'Policy Enforcement Point', 'Zero Trust Network Access', 'Identity Proving', 'Continuous Verification'],
  22: ['Third-Party Risk', 'Software Supply Chain', 'Hardware Supply Chain', 'Vendor Access', 'SBOM'],
  23: ['API Authentication', 'Rate Limiting', 'Data Exposure', 'GraphQL Introspection', 'JWT Attacks'],
  24: ['Image Vulnerabilities', 'Registry Security', 'Runtime Protection', 'CIS Benchmarks', 'Privileged Containers'],
  25: ['RBAC', 'Pod Security', 'Network Policies', 'Secrets Management', 'Admission Controllers'],
  26: ['Function Permissions', 'Event Injection', 'Cold Start Risks', 'API Gateway', 'Logging'],
  27: ['Data Poisoning', 'Model Inversion', 'Membership Inference', 'Adversarial ML', 'Supply Chain for AI'],
  28: ['Grover\'s Algorithm', 'Shor\'s Algorithm', 'QKD', 'Post-Quantum Cryptography', 'Harvest Now, Decrypt Later'],
  29: ['51% Attack', 'Smart Contract Vulnerabilities', 'Sybil Attack', 'Privacy Concerns', 'Consensus Manipulation'],
  30: ['PLC Exploitation', 'SCADA Attacks', 'Modbus Vulnerabilities', 'Air Gap Breach', 'SIS Threats'],
  31: ['EHR Breach', 'Medical Device Security', 'HIPAA Compliance', 'Patient Data Privacy', 'Ransomware in Healthcare'],
  32: ['Cardholder Data', 'PCI Scope', 'SAQ Validation', 'Tokenization', 'Merchant Breaches'],
  33: ['Payment Gateway', 'Data Leakage', 'Session Hijacking', 'Fraud Detection', 'Checkout Security'],
  34: ['User Behavior Analytics', 'Exfiltration', 'Privileged Access Abuse', 'After-Hours Activity', 'Data Hoarding'],
  35: ['Access Control Systems', 'CCTV Vulnerabilities', 'Badge Cloning', 'Visitor Management', 'Physical-cyber Convergence'],
  36: ['RTO/RPO', 'Backup Integrity', 'Alternate Sites', 'Crisis Communication', 'Tabletop Exercises'],
  37: ['Phishing Simulations', 'Social Engineering Tests', 'Security Culture Surveys', 'Executive Training', 'Gamification'],
  38: ['Asset Valuation', 'Threat Assessment', 'Likelihood/Impact', 'Mitigation Strategies', 'Risk Appetite'],
  39: ['CVE Scoring', 'Patch Prioritization', 'Vulnerability Scanning', 'Exploit Prediction', 'Remediation Tracking'],
  40: ['Recon', 'Exploit Dev', 'Post-Exploit', 'Reporting', 'Remediation Validation'],
  41: ['Scenario Planning', 'Purple Teaming', 'Threat Emulation', 'Measurement', 'Continuous Improvement'],
  42: ['NIST CSF', 'ISO 27001', 'CIS Controls', 'COBIT', 'SOC 2'],
  43: ['Cloud Evidence Collection', 'VM Forensics', 'Container Forensics', 'Log Analysis', 'Chain of Custody in Cloud'],
  44: ['Device Acquisition', 'App Forensics', 'GPS Data', 'Cloud Backups', 'Anti-Forensics'],
  45: ['Computer Fraud', 'Data Protection Laws', 'Cross-Border Data', 'Privacy Rights', 'Ethical Hacking Legality']
};

// Map iconKey to actual icon component (we'll define in icons.js)
module.exports = { MODULES, SCENARIO_TYPES };
